use_frameworks!

platform :ios, '14.1'

install! 'cocoapods', :deterministic_uuids => false

target 'KaMPKitiOS' do
    pod 'shared', :path => '../shared/'
    pod 'sharedOrbitSwift', :path => '../shared'
    pod 'SwiftLint'
    pod 'SwifterSwift/SwiftStdlib'   # Standard Library Extensions
end
